### ISSUE TITLE
[Bug] Localization issue

### ISSUE THREAD

**Issue by hienhuynhtm** [strapi/nextjs-corporate-starter#101]
I'm always get this issue when switching to other locale:
![image](https://github.com/strapi/nextjs-corporate-starter/assets/23022945/a8b2d8ef-a632-417a-b95d-65b014aacbad)

I already added more locales on Admin
![image](https://github.com/strapi/nextjs-corporate-starter/assets/23022945/b647ffbf-873a-4221-9b2e-984a95d39371)

**Comment by lorenzrabs** [comment]
How did you solve it?

**Comment by hienhuynhtm** [comment]
@lorenzrabs this error happens because I don't create `language version` for `global settings`.
By default, we only have `English version` for global, we need to create instance for `other language we need to support`

**Comment by hienhuynhtm** [comment]
Something like this
![image](https://github.com/strapi/nextjs-corporate-starter/assets/23022945/88c55874-bda8-493d-b43d-d6c799431116)

**Comment by PaulBratslavsky** [comment]
@hienhuynhtm thank you for the solution.🙂
