### ISSUE TITLE
Bug - responsive menu doesn't work correctly and overlay text and logo 

### ISSUE THREAD

**Issue by ThisIsMyName678** [strapi/nextjs-corporate-starter#103]
Bug - responsive menu doesn't work correctly and overlay text and logo 
![image](https://github.com/strapi/nextjs-corporate-starter/assets/36562028/728d45d6-8eca-4899-8365-ce5e1bcabdf4)

**Comment by PaulBratslavsky** [comment]
@ThisIsMyName678 Wow, I totally missed it.  😅 I will review it on Monday and merge it.  Thank you so much.

**Comment by PaulBratslavsky** [comment]
@ThisIsMyName678 Thank you, and merged.
