### ISSUE TITLE
site loads fine, when I refresh blog page it renders json chunks , not html

### ISSUE THREAD

**Issue by shaital** [strapi/nextjs-corporate-starter#113]
site loads fine, when I refresh blog page it renders json chunks , not html,please help
also I have noticed in the network it returns 304
also I am using strapi cache

**Comment by francostramana** [comment]
Same problem here. The error appears only in production mode.

![image](https://github.com/strapi/nextjs-corporate-starter/assets/8081236/5cefacdf-bc6e-41eb-bbbd-10c71bf580ce)

**Comment by shaital** [comment]
Got the solution
add: export const revalidate = 0; in app/layout.js file.
This will solve the problem
