### ISSUE TITLE
No documentation on deploying to Vercel

### ISSUE THREAD

**Issue by conor909** [strapi/nextjs-corporate-starter#116]
I found this template from [the vercel template page.](https://vercel.com/new/clone?demo-description=Strapi%20demo%20application%20for%20Corporate%20Websites%20using%20Next.js%2013%20App%20Router%2C%20Tailwind%2C%20Typescript.&demo-image=%2F%2Fimages.ctfassets.net%2Fe5382hct74si%2F6y6Q9m0lheMRUlCxfAuNX9%2F83fd86cc8c51432ee3263094d1f0080f%2FCleanShot_2023-05-15_at_10.49.57.png&demo-title=Strapi%20Next.js%20Corporate%20Website%20Starter&demo-url=https%3A%2F%2Fstrapi-starter-local-setup.vercel.app%2Fen&env=NEXT_PUBLIC_STRAPI_API_TOKEN%2CNEXT_PUBLIC_STRAPI_FORM_SUBMISSION_TOKEN%2CNEXT_PUBLIC_STRAPI_API_URL%2CNEXT_PUBLIC_PAGE_LIMIT&envDescription=How%20to%20get%20these%20env%20vars%3A&envLink=https%3A%2F%2Fgithub.com%2Fstrapi%2Fnextjs-corporate-starter%23setting-up-the-frontend&from=templates&project-name=Strapi%20Next.js%20Corporate%20Website%20Starter&repository-name=strapi-nextjs-corporate-starter&repository-url=https%3A%2F%2Fgithub.com%2Fstrapi%2Fnextjs-corporate-starter&root-directory=frontend&skippable-integrations=1)  I cloned the repo and set up locally, but how do I deploy to vercel?  If I try to set it up from the template page, it says I need to add my environment variables first.  But how do I do that if my backend is not setup yet?

**Comment by PaulBratslavsky** [comment]
There is no auto deploy option for Strapi on Vercel. You have to deploy you Strapi application separately.   

You can use Render, Digital Ocean or even Strapi Cloud as outline [here](https://www.youtube.com/watch?v=qHqzUdC7xaI)

And after wards you would deploy your Next JS application to Vercel.  As explained [here](https://www.youtube.com/watch?v=SkKFHcCACr4)

**Comment by Nazehs** [comment]
@PaulBratslavsky Quick question what was the point of using a monorepo for both frontend & backend if both can't be deployed together?

**Comment by PaulBratslavsky** [comment]
@Nazehs just so I can have one repo for the project when working on it. When deploying the app on Vercel I use the same repo but point to frontend, and when deploying the backend on Digital Ocean I use the same repo and point to the `backend` folder.
