### ISSUE TITLE
Reference Error: window is not defined? 

### ISSUE THREAD

**Issue by custards** [strapi/nextjs-corporate-starter#121]
Hey! Relatively new to this so I just wanted to purely follow the tutorials to setup the template project to tinker around with. Unfortunately, when running "yarn dev" with the frontend, I get the error below along with the site just being a blank page. I could be missing something so apologies if it's silly but I've already created an admin account and set the tokens in the backend. Generated some random strings for the frontend .env file.

ReferenceError: window is not defined
    at RootRoute (./src/app/[lang]/page.tsx:27:9)
  19 |       )
  20 |     } catch (error: any) {
> 21 |       window.alert('Missing or invalid credentials')
     |      ^
  22 |     }
  23 | }
  24 |

**Comment by PaulBratslavsky** [comment]
This error is thrown when you add invalid API Token in your frontend.  Make suer you added the correct token in your frontend .env file.

```
NEXT_PUBLIC_STRAPI_API_TOKEN=your-api-token
NEXT_PUBLIC_PAGE_LIMIT=6
NEXT_PUBLIC_STRAPI_FORM_SUBMISSION_TOKEN=your-form-submission-token
NEXT_PUBLIC_STRAPI_API_URL=http://localhost:1337

```

**Comment by ugoarzur** [comment]
Hi 👋🏻 

I was curious to give it a try but I found this very same issue although I followed [this guide from Vercel](https://vercel.com/templates/next.js/strapi-nextjs-corporate-starter), generated my api tokens from the strapi dashboard and inserted them into my `frontend/.env` file.

I am not a frontend expert but (to me) `window is not defined` seems more related to a frontend absence of the `window` because the components may have been generated from the server.
According to the [Next.js SSR Component Documentation](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering) this behaviour is an SSR component and therefore there is no window in server. 

> _To use Server-side Rendering for a page, you need to `export` an `async` function called getServerSideProps. This function will be called by the server on every request._

**Comment by PaulBratslavsky** [comment]
@ugoarzur I am going to see if I can reproduce your issue, in terms of the link you shared [here](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering) it refers to the pages folder structure, but here we are using app router. 

I will see if I can recreate it and see if I get the same issue.  Thank you for bringing this to my attentiion.

**Comment by PaulBratslavsky** [comment]
@ugoarzur I just did the set up to test the app and everything worked.  Here is the video I recorded as I was trying to reproduce you issue.  

https://github.com/strapi/nextjs-corporate-starter/assets/6153188/fcf42385-efd0-4926-92df-a434aeeaf846

Also, we have open office hours on Strapi's Discord, you can stop by and we can look at your issue together.

https://discord.com/invite/strapi

Mon - Fri 12:30 PM CST time.

**Comment by custards** [comment]
Hey! I really appreciate your help with the issue and even providing a walkthrough. I was actually able to get it to work by regenerating more tokens. Only difference was that I set a duration of unlimited this time instead of 7 days when I first reported the issue. Couldn't really say why this had the effect it did as I did try new tokens multiple times but maybe something was botched on my end that I didn't notice.

**Comment by locnt19** [comment]
HI @custards, Could you try creating an API with Full Access and put it in the .env file in the frontend folder to try to resolve this issue? If it works, you can change the API Token permission later.

![image](https://github.com/strapi/nextjs-corporate-starter/assets/38103796/fee8dcdc-4f62-486c-ae39-1248fdc497b8)

![image](https://github.com/strapi/nextjs-corporate-starter/assets/38103796/397ccdca-60a4-407d-9a16-e7e29150da3a)
