### ISSUE TITLE
Error during install dependencies.

### ISSUE THREAD

**Issue by crazy-man22** [strapi/nextjs-corporate-starter#15]
![Screenshot from 2023-04-27 10-41-25](https://user-images.githubusercontent.com/61251512/234946870-e716c8e0-70f1-47c7-8a91-cb7a6660dfb3.png)

As you can see in the image above, the error comes from `better-sqlite` package.
This repo uses `better-sqlite@7.4.6`. and it seems that it is not working with v18.x.x of the node.js.

I upgraded the version of `better-sqlite` as a latest one. and then it works.

My node.js version is 18.12.1.

**Comment by PaulBratslavsky** [comment]
I am using node version `v18.14.2` and have no issues.  I am using "better-sqlite3": "7.4.6".

But I will upgrade it to the latest to avoid issues just in case.

Will be closing this issue.  Thanks for the help.
