### ISSUE TITLE
Create a deployment guide to Vercel and Strapi Cloud

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/nextjs-corporate-starter#22]

**Comment by git-asia** [comment]
Great idea! I'm looking forward to see that.

**Comment by PaulBratslavsky** [comment]
@git-asia I started working on it.  I am just waiting for the transfer feature to be finished so I can show how to transfer your local data to Strapi Cloud via the 'yarn strapi transfer' feature.

**Comment by Hudsonzp** [comment]
Definitely needed. Having trouble deploying the Vercel side as we speak.

**Comment by zchwyng** [comment]
I'm having issues to deploy it to Vercel as well. Works fine locally, but it can't find the Strapi API (since it's not been deployed yet) So I feel kind of stuck right now. Any help/pointers is greatly appreciated!

**Comment by PaulBratslavsky** [comment]
First I would recommend deploying the Strapi application.  Good hosting options are Render or Digital Ocean once it is deployed you can deploy to Vercel.  I have made this video series that walk through the process. It should get you going.  

https://youtube.com/playlist?list=PL7Q0DQYATmvjZjamfD8yMYYH8GeVs3hCd&feature=shared 

Will be closing this issue since the Deployment Videos Are available now.
