### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by KennyAtCodin** [strapi/nextjs-corporate-starter#24]
` [2023-05-22 16:51:33.069] error: [FATAL] Invalid schema changes detected during integrity checks (using the strict strategy). Please find a summary of the changes below:
- admin::permission:
  -  exists in destination schema but not in source schema
- admin::user:
  -  exists in destination schema but not in source schema
- admin::role:
  -  exists in destination schema but not in source schema
- admin::api-token:
  -  exists in destination schema but not in source schema
- admin::api-token-permission:
  -  exists in destination schema but not in source schema
- admin::transfer-token:
  -  exists in destination schema but not in source schema
- admin::transfer-token-permission:
  -  exists in destination schema but not in source schema
- plugin::upload.file:
  -  exists in destination schema but not in source schema
- plugin::upload.folder:
  -  exists in destination schema but not in source schema
- plugin::i18n.locale:
  -  exists in destination schema but not in source schema
- plugin::users-permissions.permission:
  -  exists in destination schema but not in source schema
- plugin::users-permissions.role:
  -  exists in destination schema but not in source schema
- plugin::users-permissions.user:
  -  exists in destination schema but not in source schema
- api::article.article:
  -  exists in destination schema but not in source schema
- api::author.author:
  -  exists in destination schema but not in source schema
- api::category.category:
  -  exists in destination schema but not in source schema
- api::global.global:
  -  exists in destination schema but not in source schema
- api::lead-form-submission.lead-form-submission:
  -  exists in destination schema but not in source schema
- api::page.page:
  -  exists in destination schema but not in source schema
- api::product-feature.product-feature:
  -  exists in destination schema but not in source schema
- elements.feature-column:
  -  exists in destination schema but not in source schema
- elements.feature-row:
  -  exists in destination schema but not in source schema
- elements.feature:
  -  exists in destination schema but not in source schema
- elements.footer-section:
  -  exists in destination schema but not in source schema
- elements.logos:
  -  exists in destination schema but not in source schema
- elements.notification-banner:
  -  exists in destination schema but not in source schema
- elements.plan:
  -  exists in destination schema but not in source schema
- elements.testimonial:
  -  exists in destination schema but not in source schema
- layout.footer:
  -  exists in destination schema but not in source schema
- layout.logo:
  -  exists in destination schema but not in source schema
- layout.navbar:
  -  exists in destination schema but not in source schema
- links.button-link:
  -  exists in destination schema but not in source schema
- links.button:
  -  exists in destination schema but not in source schema
- links.link:
  -  exists in destination schema but not in source schema
- links.social-link:
  -  exists in destination schema but not in source schema
- meta.metadata:
  -  exists in destination schema but not in source schema
- sections.bottom-actions:
  -  exists in destination schema but not in source schema
- sections.feature-columns-group:
  -  exists in destination schema but not in source schema
- sections.feature-rows-group:
  -  exists in destination schema but not in source schema
- sections.features:
  -  exists in destination schema but not in source schema
- sections.heading:
  -  exists in destination schema but not in source schema
- sections.hero:
  -  exists in destination schema but not in source schema
- sections.large-video:
  -  exists in destination schema but not in source schema
- sections.lead-form:
  -  exists in destination schema but not in source schema
- sections.pricing:
  -  exists in destination schema but not in source schema
- sections.rich-text:
  -  exists in destination schema but not in source schema
- sections.testimonials-group:
  -  exists in destination schema but not in source schema
- shared.media:
  -  exists in destination schema but not in source schema
- shared.quote:
  -  exists in destination schema but not in source schema
- shared.rich-text:
  -  exists in destination schema but not in source schema
- shared.seo:
  -  exists in destination schema but not in source schema
- shared.slider:
  -  exists in destination schema but not in source schema
- shared.video-embed:
  -  exists in destination schema but not in source schema
Import process failed.
error Command failed with exit code 1. `

**Comment by PaulBratslavsky** [comment]
@KennyAtCodin I just recently tested this from the most current update and I could not replicate the issue.  

Which version of Strapi are you using, also if possible can you add the steps to reproduce the issue. 

It would be very helpful, thank you.

**Comment by KennyAtCodin** [comment]
@PaulBratslavsky: I was using 4.9.2. The version that I cloned, the starter. Manually updated to 4.10.5, then the import went through, but all the media files were missing in the demo content. Therefore the frontend didn't work.

**Comment by KennyAtCodin** [comment]
Still no images, maybe it has something to do with windows... will try it on wsl later

**Comment by PaulBratslavsky** [comment]
> Still no images, maybe it has something to do with windows... will try it on wsl later

Thank you, let me know if that works for you.  I will also test in windows and see if I can reproduce the issue.

**Comment by KennyAtCodin** [comment]
@PaulBratslavsky: in wsl (ubuntu 22.04) it works. I think it's something windows specific.

**Comment by KennyAtCodin** [comment]
Tested again on Windows. Works as well.
