### ISSUE TITLE
Confusing documentation of .env.example 

### ISSUE THREAD

**Issue by spaceo** [strapi/nextjs-corporate-starter#28]
In the README.md file it says that you can copy the `.env.example` to create your own `.env`file.
But there is no such example file in the root of the project.

<img width="596" alt="image" src="https://github.com/strapi/nextjs-corporate-starter/assets/998889/866c4fd7-cd68-47fe-9bff-37c12399720b">

UPDATE:
After some digging I found it lying in the backend directory. I think the documentation should be clearer about that.

**Comment by PaulBratslavsky** [comment]
@spaceo Thanks for the feedback will make it more clear and publish the update.

**Comment by PaulBratslavsky** [comment]
Thank you, made the changes in this PR and merged. https://github.com/strapi/nextjs-corporate-starter/pull/31
