### ISSUE TITLE
Wrong API token name in documentation

### ISSUE THREAD

**Issue by spaceo** [strapi/nextjs-corporate-starter#29]
In the README.md it says:
_Once you have your token add it to your `NEXT_STRAPI_API_TOKEN` variable name in the `.env` file._

The name of the token must have changed since it was written. I believe it is now called: `NEXT_PUBLIC_STRAPI_API_TOKEN`?

**Comment by PaulBratslavsky** [comment]
@spaceo Thanks you are correct.  I will make the update.
