### ISSUE TITLE
Frontend cannot load

### ISSUE THREAD

**Issue by spaceo** [strapi/nextjs-corporate-starter#30]
I get following error in the browser and in Node:
Unhandled Runtime Error
Error: Cannot read properties of null (reading 'attributes')

<img width="891" alt="image" src="https://github.com/strapi/nextjs-corporate-starter/assets/998889/00191445-1174-4a0a-bb7e-83f2c4ed9ab2">

**Comment by Phillyphus** [comment]
Ran into the same issue and it prevented me from building the project. Rebuilt the project a few times to make sure I was following steps correctly but no success.

**Comment by PaulBratslavsky** [comment]
@spaceo and @Phillyphus I will take a look at this when get a chance, but in the mean time you can check if a log exists inside your Strapi Admin.  

![2023-05-25_15-46-08](https://github.com/strapi/nextjs-corporate-starter/assets/6153188/99acc1d4-c3bb-4e35-bbac-382bcb4380e5)

I will make a video outlining the steps of setting up this project.  Just to make it easier to get started with and see if I get the same error. 

Thank you both for the feedback.

**Comment by spaceo** [comment]
I don't know where to find logs in the Strapi admin interface. But if I compare your screenshot with what I see in the global config I notice that I am missing the `logo-dark.png` image that I see in your screenshot. And the errors I mentioned before are just about that.

**Comment by spaceo** [comment]
I have now seen other places in Strapi content where images are missing. I see a pattern here :)

**Comment by cjsewell** [comment]
I had a similar issue where  ` yarn strapi import -f ../seed-data.tar.gz` doesn't seem to link all images correctly?

Can work around it by manually setting the missing image relations after importing.

Could this be a bug in the import or a bad seed-data.tar.gz?

**Comment by PaulBratslavsky** [comment]
@spaceo @cjsewell thanks for the feedback I will take a look and see if I need to update the seed data file or if there is actually a bug on import.

@spaceo but yeah the `yarn strapi import` should of added all those files.

**Comment by PaulBratslavsky** [comment]
@spaceo @cjsewell update: I was able to replicate on import not getting all the image relationships set.

https://github.com/strapi/nextjs-corporate-starter/assets/6153188/6dcca2f1-a4b6-4ede-930c-b990b035ba89

There is a DTS issue that should fix this with the release of 4.10.7 you can see the PR [here](https://github.com/strapi/strapi/pull/16842)

**Comment by PaulBratslavsky** [comment]
UPDATE: I confirmed that there were breaking changes in 4.10.5 so I will revert the main project to 4.10.4 where Import works as expected util the release of 4.10.7

**Comment by karuna001** [comment]
Command failed with exit code 1.
how to solve this error?

**Comment by karuna001** [comment]
-  ┌ GET /favicon.ico 200 in 186ms
   │
   ├──── GET http://localhost:1337/api/pages?filters%5Bslug%.. 401 in 37ms (cache: MISS)
   │
   └──── GET http://localhost:1337/api/global?populate%5B0%5D.. 401 in 48ms (cache: MISS)


how to solve this issue bro?

**Comment by KennyAtCodin** [comment]
@karuna001: probably an issue with the tokens, did you set the NEXT_PUBLIC_STRAPI_FORM_SUBMISSION_TOKEN and the NEXT_PUBLIC_STRAPI_API_TOKEN?

**Comment by PaulBratslavsky** [comment]
@karuna001 I will make a video outlining the setup process for the Strapi Starter hopefully that will help.  I had no issues setting up the project when I tested it recently.
