### ISSUE TITLE
Change "getStrapiURL" to "getStrapiMedia" in Testimonials.tsx file 

### ISSUE THREAD

**Issue by paulnotfromstrapi** [strapi/nextjs-corporate-starter#41]
"getStrapiURL" should be changed to "getStrapiMedia" 

https://github.com/strapi/nextjs-corporate-starter/blob/014e4dd4bfcccbe499a51a234d68fd079d7b814e/frontend/src/app/%5Blang%5D/components/Testimonials.tsx#L29

https://github.com/strapi/nextjs-corporate-starter/blob/main/frontend/src/app/%5Blang%5D/components/Testimonials.tsx

**Comment by PaulBratslavsky** [comment]
Done
