### ISSUE TITLE
.env cant make develop

### ISSUE THREAD

**Issue by slowpack** [strapi/nextjs-corporate-starter#44]
![image](https://github.com/strapi/nextjs-corporate-starter/assets/38886805/a55e83b8-26a7-489b-a5ca-62a6f379456e)
i am a rookie 
I dont know where get the app_keys and tokens...
so i use example the 1337 developed but i cant visit it  
after few hours  finaly find the problem is .env
so i use the .env from when i first use yarn create strapi-app my-project --quickstart to build a strapi pro 
finally it work 

HOST=0.0.0.0
PORT=1337
APP_KEYS=tzxxA==
API_TOKEN_SALT=VreRxx==
ADMIN_JWT_SECRET=Yi9xx==
TRANSFER_TOKEN_SALT=+Zx8xx==
# Database
DATABASE_CLIENT=sqlite
DATABASE_FILENAME=.tmp/data.db
JWT_SECRET=QPNxx==

but i find host is diffrent from example ! its 0.0.0.0 so i change to localhost then i cant visit 😭
maybe problem is  iam useing ssh connect to linux server and use docker to develop idk 😵‍💫
but ty PaulBratslavsky , i see you video in youtobe,its very helpful , i rember you prefer remix so why here is next XD

**Comment by PaulBratslavsky** [comment]
@slowpack Thanks for sharing.  Yeah it might have something to do with Docker.  

I don't use Docket but maybe a good idea to create a guide on how to set the project up with Dicker.

Yeah in terms of env file you need to fill it in with you variables and settings.

**Comment by slowpack** [comment]
Yes，strapi and node version and centos version and sharp gives me a headache XD .
i use centos 7,it Does not work well with Node 18.
i try 16 ,but there are still many problems when downloading the package .
so i try docker use 18 , its convenient, except when downloading  sharp 😂
Here are a few of my simple docker command
```
FROM node:lts
# RUN yarn config set registry xx(if you need,for me is helpful)
# RUN yarn config set sharp_binary_host "https://xx/mirrors/sharp"
# RUN yarn config set sharp_libvips_binary_host "https://xx/mirrors/sharp-libvips"
```

```bash
docker image build -t name:tag .
# . means Current directory
```
```bash
docker run --name strapi-template -p 1337:1337\
    -v /xx/nextjs-corporate-starter:/strapi-template\
    -it node:lts(The name:tag) /bin/bash
# -v     Map the system file to the docker container
```
Next, we can do next in the docker's  bash,but first cd to /strapi-template(The name you chose)

**Comment by PaulBratslavsky** [comment]
@slowpack not sure if you new, there is a cli tool that makes dockerizing Strapi a bit easier, you can check it out here https://blog.dehlin.dev/docker-with-strapi-v4
