### ISSUE TITLE
I encountered an issue when trying to add a component to the home page. The component is not appearing or functioning as expected.

### ISSUE THREAD

**Issue by santneuv** [strapi/nextjs-corporate-starter#45]
![image](https://github.com/strapi/nextjs-corporate-starter/assets/56323508/85b97306-c014-4c07-ab19-d6dee008d59b)
Hi there newbie here i want to add a new component to home page but am i missing something? wherer should i define the components for the home page

Thank you for your attention to this matter. Let me know if any further information is required.

**Comment by santneuv** [comment]
hey again i found the solution i really misunderstand the logic of strapi :D but if u got any tips for that i could use that.
thanks again

**Comment by PaulBratslavsky** [comment]
@santneuv Glad you found the solution.  But just to review the basic flow.

The page content type in Strapi has a dynamic zone section.

So you would first add a component to the dynamic zone and then create a component to consume that data in your Next JS project and add it to the rendered switch statement.

If you have any additional questions feel free to ask.  You can also join the Strapi discord server and ask questions there as well. 

We have an open office hour Monday through Friday from 12:30 PM CST.
