### ISSUE TITLE
Navbar and Footer not displaying localized content from Strapi CMS in Next.js

### ISSUE THREAD

**Issue by AnasGamal** [strapi/nextjs-corporate-starter#58]
Bug Description:
Next.js Navbar and Footer components do not display localized content that should be fetched from Strapi CMS,. Despite creating localized versions in different languages and adding language-specific content to the header and footer sections in the Strapi CMS, the website only shows the default _(i suppose)_ locale content for the Navbar and Footer across all languages.

Steps to Reproduce:
1. Go to the Content Manager in Strapi CMS.
2. Select `Global` under `Single Type`.
3. Create a localized version in another language.
4. Add language-specific content to the header and footer or any other sections.
5. Save the changes.
6. View the website in the selected language.

Expected Result:
All homepage sections, including the Navbar and Footer, should display the localized content specific to the selected language.

Actual Result:
The Navbar and Footer components continue to display the default locale content across all languages, instead of the expected localized content.

**Comment by AnasGamal** [comment]
I think the issue stems from the way "Global" single content type data is fetched from Strapi API in `frontend/src/app/[lang]/layout.tsx`.

The issue also affects meta data from my experience.

**Comment by AnasGamal** [comment]
I created pull request #60 related to this issue, please review it and merge it if it's possible.

**Comment by PaulBratslavsky** [comment]
You are the best @AnasGamal thank you.
