### ISSUE TITLE
What is the purpose of `fixed-data.tar.gz`?

### ISSUE THREAD

**Issue by mnzaki** [strapi/nextjs-corporate-starter#6]
it seems slightly different from `seed-data.tar.gz` but also only appears mysteriously in strapi@f87bb345bf7b6e1464456ef195deba69fea2f83d

**Comment by PaulBratslavsky** [comment]
@mnzaki thank you for letting me know. That file should be removed.🙂

**Comment by PaulBratslavsky** [comment]
Removed fixed-data.tar.gz file.
