### ISSUE TITLE
Redundant code for home page and [...slug]/page

### ISSUE THREAD

**Issue by KennyAtCodin** [strapi/nextjs-corporate-starter#63]
It would be nice if we could handle the "home route" with the same code as all the other pages. The home page should not be treated differently.

What I can think of is redirecting the home page to a slug page. Not sure though if Next.js could handle that. Maybe someone with more knowledge can help on this (if you point me in the right direction, I'm happy to implement it myself)

**Comment by PaulBratslavsky** [comment]
@KennyAtCodin hope you are doing great.  That is a great question.  I will have to do some more research and see what Next recommends. If you find anything feel free to share.

**Comment by KennyAtCodin** [comment]
I currently did something for one of my clients:

`import {redirect} from "next/navigation";


export default async function RootRoute({params}: { params: { lang: string } }) {
    redirect(`${params.lang}/home`)
}`

It works - but I'm currently trying to figure out what influence this has on SEO performance, but my SEO guy is currently enjoying his vacation.

**Comment by PaulBratslavsky** [comment]
@KennyAtCodin ok cool thank you for sharing.  I am very interested what he will say.  Since it would simplify the code.

**Comment by PaulBratslavsky** [comment]
Will be closing this for now to clean up the issues in repo since this is not a breaking issue.  Will revisit once get more info.
