### ISSUE TITLE
Category Slug Generation Doesn't Reflect Category's Name

### ISSUE THREAD

**Issue by AnasGamal** [strapi/nextjs-corporate-starter#64]
Issue:
Currently, when the "generate" button is pressed to create a category slug, it always outputs "category" regardless of the actual category name.

Expected Behavior:
The category slug generation should be based on the category's name. For example, if the category's name is "strapi," the slug should be automatically generated as "strapi" if it's available. If a slug with the same name already exists, it should generate a unique slug like "strapi-1" or similar.

**Comment by AnasGamal** [comment]
I created pull request #65 which addresses this issue. Please review and merge if possible.

**Comment by PaulBratslavsky** [comment]
@AnasGamal I will take a look. Apologies for the delay.  Wanted to wait for the Strapi 4.12.1 update and fixes before making changes.
