### ISSUE TITLE
exception when loading blog

### ISSUE THREAD

**Issue by codegod100** [strapi/nextjs-corporate-starter#78]
![image](https://github.com/strapi/nextjs-corporate-starter/assets/78769380/138923aa-405f-455f-a7cd-901b65ad248f)

**Comment by PaulBratslavsky** [comment]
@codegod100 I just tested the Strapi Starter with next and did not run into any issues.  You can try to do a clean install and compare to your current project.  

Also, when you console log data, what are you returning?

**Comment by codegod100** [comment]
`data` is `[]`

**Comment by PaulBratslavsky** [comment]
Did you import the 'seed-data'?

We are also now (12:35 pm cst) time in open office hours on discord.  

If you want to jump on and share your screen.

**Comment by codegod100** [comment]
I missed the open office hours. I imported the seed data. Maybe something went wrong during import, I can start again.

**Comment by PaulBratslavsky** [comment]
@codegod100 let me know how it goes.  Thank you.

**Comment by PaulBratslavsky** [comment]
I am going to close this issue for the time being, if you are still stuck.  You can hit me up on Discord. Or just mention me here.
