### ISSUE TITLE
node version problem

### ISSUE THREAD

**Issue by kadirkatirci** [strapi/nextjs-corporate-starter#84]
i got this error when i run "yarn setup" for one of the module 

if i use "--ignore-engines" it is okay but this time gives error for backend build

The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.4.0".

**Comment by paulnotfromstrapi** [comment]
@kadirkatirci currently the starter supports node 18.  If you are using NVM, install node 18 and try again.

**Comment by kadirkatirci** [comment]
Thank you

**Comment by PaulBratslavsky** [comment]
@meotimdihia thank you for the comment.  I will add it to the todo to update the project to support node 20
