### ISSUE TITLE
How to get images from public folder in this app

### ISSUE THREAD

**Issue by asifdastagir-ovrlod** [strapi/nextjs-corporate-starter#90]
How to get images form a public folder in this app??

**Comment by aarajbhattarai** [comment]
add the file path in middleware.tsx.

`export function middleware(request: NextRequest) {
    const pathname = request.nextUrl.pathname;

    // // `/_next/` and `/api/` are ignored by the watcher, but we need to ignore files in `public` manually.
    // // If you have one
    if (
        [
            '/manifest.json',
            '/favicon.ico',
            '/robots.txt',
            '/sitemap.xml',
            
            // Your other files in `public`
        ].includes(pathname)
    )
        return;`

**Comment by PaulBratslavsky** [comment]
@aarajbhattarai thank you for your awesome help with the answer I will close this issue now.
