### ISSUE TITLE
Uncaught Error: invariant expected app router to be mounted

### ISSUE THREAD

**Issue by jj6990** [strapi/nextjs-corporate-starter#91]
![Screen Shot 2023-10-17 at 08 30 54](https://github.com/strapi/nextjs-corporate-starter/assets/35140255/2f4da1df-c813-4326-a64b-fe4b0e8e1e2a)
Does anyone knows why is this issue happening?
node 16.8.0

**Comment by PaulBratslavsky** [comment]
I will try to reproduce. But so far I haven't seen this error.  But I am also on node 18.  Not sure if it makes a difference though.

**Comment by PrimeTimeTran** [comment]
Ditto from me.
<img width="1728" alt="Screenshot 2023-10-20 at 4 29 16 AM" src="https://github.com/strapi/nextjs-corporate-starter/assets/16382165/e5a3e7ba-ba7d-4bea-95fb-f7314294d67b">
<img width="1728" alt="Screenshot 2023-10-20 at 4 29 11 AM" src="https://github.com/strapi/nextjs-corporate-starter/assets/16382165/d10a2b33-2104-45e2-a276-4533d19d8dd6">

**Comment by PrimeTimeTran** [comment]
I figured it out, need to actually set up the token, I thought it was just a meaningless placeholder. Thanks for your work!

https://www.youtube.com/watch?v=a23JvssqrrQ&ab_channel=Strapi

**Comment by PrimeTimeTran** [comment]
Just a suggestion, an error message/prompt might be helpful for future users.

**Comment by jj6990** [comment]
Thanks guys for your help this actually worked for me as well not sure why in production worked normally and locally it didn't

**Comment by PaulBratslavsky** [comment]
Thank you all amazing folks.  @PrimeTimeTran if you have time, would you like to make a PR for it?

**Comment by PrimeTimeTran** [comment]
@PaulBratslavsky your wish is my command. lol =).

https://github.com/strapi/nextjs-corporate-starter/pull/96

**Comment by PaulBratslavsky** [comment]
@PrimeTimeTran you are awesome.  Thank you and merged.
https://github.com/strapi/nextjs-corporate-starter/pull/96

**Comment by ankycheng** [comment]
For me, to resolve this error I also have to set up metadata/ global properties in the admin if you are working on a brand new project. Otherwise, lacking of these data will cause rendering errors.
