### ISSUE TITLE
The Application does not load an image in the background 

### ISSUE THREAD

**Issue by edergermanio1980** [strapi/nextjs-corporate-starter#94]
The Application does not load an image in the background of the hero section, I used the extend backgroundImage from the tailwind.config.js file to load the image, but the image does not load

<img width="646" alt="image" src="https://github.com/strapi/nextjs-corporate-starter/assets/66970649/6a0aabc3-b092-4fa6-b9e8-fa040e7a7a67">

<img width="909" alt="image" src="https://github.com/strapi/nextjs-corporate-starter/assets/66970649/c7ca90c0-b600-4591-b32f-1f67d5ee1c86">

<img width="655" alt="image" src="https://github.com/strapi/nextjs-corporate-starter/assets/66970649/0ae6038b-b902-4d43-863d-3dc6351095ea">

**Comment by PaulBratslavsky** [comment]
I don't think the error you are showing is the same error for not loading images.  Can you console log `page.data[0]` to see what you are getting.   

In any case if something is missing it should fall back to `FALLBACK_SEO`, maybe changing it to the following will fix the original error.

```
  if (!page.data[0]?.attributes?.seo;
```

Let me know if that helps or if you get another error.

**Comment by PaulBratslavsky** [comment]
Closing due to "no recent activities"
