### ISSUE TITLE
How do I deploy a backend to Vercel separately? Always 404

### ISSUE THREAD

**Issue by fwh666** [strapi/nextjs-corporate-starter#98]
How do I deploy a backend to Vercel separately? Always 404

**Comment by PaulBratslavsky** [comment]
@fwh666 you can't deploy Strapi on Vercel, need to use Render, Heroku, Digital Ocean, etc.

I have the frontend deployed on Vercel and backed  deployed on digital ocean.

**Comment by maksym-arturIn** [comment]
Can you add a "How to deploy" guide with deploy  instruction on Render/Heroku/DigitalOcean for the app(backand with frontend) ?

**Comment by maksym-arturIn** [comment]
@PaulBratslavsky Did you have any problem with image optimization requests when deploy on Vercel?
